PREFIX = /usr/local

obj = src/cpumon.o src/main.o src/memmon.o src/options.o src/irix/cpu.o \
	  src/irix/mem.o
bin = xmon

CFLAGS = -g3 -Isrc
LDFLAGS = -lX11 -lXext

$(bin): $(obj)
	$(CC) -o $@ $(obj) $(LDFLAGS)

.c.o:
	$(CC) -o $@ $(CFLAGS) -c $<

.PHONY: clean
clean:
	rm -f $(obj) $(bin)

.PHONY: install
install: $(bin)
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	cp $(bin) $(DESTDIR)$(PREFIX)/bin/$(bin)

.PHONY: uninstall
uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/$(bin)
